### ISSUE TITLE
Getting error, when the train data contains word 'constructor'

### ISSUE THREAD

**Issue by martynassimkevicius** [andreekeberg/ml-classify-text-js#10]
`tokens` is an object with key of words from input, so if one of words is `constructor`, then check fails.

https://github.com/andreekeberg/ml-classify-text-js/blob/d8b18d2c17a6d03170bb65848d26ba6725bd4dfe/src/classifier.js#L223

**Comment by Pumych** [comment]
Same for me, getting the following error, which is confused me little bit
` */u.default=function(d){if(!d.addUnicodeData)throw new ReferenceError("Unicode Base must be loaded before Unicode Scripts");d.addUnicodeData(n.default)},`

**Comment by andreekeberg** [comment]
Hi guys, sorry for the lack of updates on this.

I completely understand that this project might seem abandoned at this point, but much of the delays have been because I started working on a new version with quite a lot of changes, and was a bit optimistic on the timeline, thinking I would take care of both this and another issue as a part of this new update.

However since this proved to take a lot more time than planned, I'll make sure to prioritize this issue over the work on the new major version and have a fix for it ready as a patch version as soon as possible.

Thanks a lot for your patience and for your continued interest in the project!

**Comment by andreekeberg** [comment]
Fixed in #11
