### ISSUE TITLE
Cannot add vocabulary

### ISSUE THREAD

**Issue by Triplecorpse** [andreekeberg/ml-classify-text-js#12]
![image](https://github.com/andreekeberg/ml-classify-text-js/assets/11461770/e24c7a93-e467-4a33-ba50-0894e6d380a4)
This is a screenshot from Webstorm. As you can see, parsed.vocabulary is set and I tried to insert it into classified both in the constructor and in model itself.

However, the vocabulary was not set in model.

Is that fixable?

**Comment by Triplecorpse** [comment]
I was confused with my own code, sorry

**Comment by andreekeberg** [comment]
@Triplecorpse Hi, I was just about to look into this and also thank you for using this library even though I unfortunately haven't had time to properly maintain it for quite some time! Happy to hear that you resolved the issue! 

I've been working on a new version that will improve quite a lot of aspects, including very significant performance enhancements, support for stop words and custom tokenizers as well as making the `train` and `predict` methods asynchronous - and seeing that the project is still being this actively used is definitely a well needed push for me to actually prioritize getting this done as soon as possible! 🥳

**Comment by Triplecorpse** [comment]
Thank you. Actually classifier.model.serialize gives me a vocabulary so I think I might be missing something in my code. I haven't found it yet but I will. Thank you for the reply

**Comment by andreekeberg** [comment]
I see, sorry to hear this! It might be an unrelated bug, but I should mention that normally you shouldn't really need to manipulate the vocabulary directly, as these tokens are automatically created and added to the vocabulary when you `train` the model. You can then `serialize` the model at any point in its current state, and later load the full model it into the classifier again by passing it to the constructor (as I see you're doing by passing `parsed`, which I assume is a serialized model, otherwise this might actually be the source of your problem, especially since you mention getting back a vocabulary rather than a model from `serialize`).

Any changes to the vocabulary that takes place outside of the internal logic, where the `train` method tokenizes the provided input and adds any non-existent tokens to the vocabulary would almost certainly break the model, as the tokens and/or their indexes in the vocabulary would no longer match the associated indexes in the model `data`.

Is there any specific reason you are directly manipulating the vocabulary?

I see that you have trained the model with Cyrillic text, and while the basic [XRegExp](https://github.com/slevithan/xregexp) pattern used in the internal `splitWords` method, `XRegExp('\\P{L}+', 'g')` should actually handle all Unicode alphabets including Cyrillic, I haven't tested this fully, but I can imagine that this might have been the reason you decided to manually alter the vocabulary, i.e. to fix any tokenization issue?

If that is the case, you might have to wait until the next version is released where custom `tokenizer` functions will be supported, otherwise you might be able to override the `splitWords` method by doing something like below, but I cannot test this right now so can't guarantee anything:

```js
const classifier = new Classifier()

classifier.splitWords = (input) => {
	if (typeof input !== 'string') {
		throw new Error('input must be a string')
	}

	// Remove all apostrophes and dashes to keep words intact
	input = input.replace(/'|´|’|-/g, '')

	// Lowercase all letters and replace all non-letter characters with a space
	input = XRegExp.replace(
		input.toLocaleLowerCase(),
		XRegExp('\\P{L}+', 'g'), // Make any necessary changes to this pattern to fix possible issues with Cyrillic
		' '
	).trim()

	return input.split(' ')
}

// Use the classifier like normally...
```

However this would also require you to re-train a new model from scratch since the new tokens created as a result of this change when calling `train` and `predict` would have to match the ones present in any existing vocabulary.

Sorry to hear that you are experiencing these problems, and I hope that you will either be able to work around it yourself, or that I'll be able to release the next version soon enough!

**Comment by Triplecorpse** [comment]
Thank you. However, it was my issue indeed. I thought that Webstorm should show Sets but it seems that for some reason it didn't. I removed all my code and rewrote it from scratch, testing each step. I really appreciate you involved help but it was my issue. Sorry for bothering you. The Cyrillic text is okay.
I really wait for new version because you mentioned async operations - I really miss it. I needed to create an async wrapper. And you mentioned about performance upgrade. Not so much, but I wait it too. Thank you, this particular issue is closed
