### ISSUE TITLE
Is it possible to save training data?

### ISSUE THREAD

**Issue by ronaldaug** [andreekeberg/ml-classify-text-js#7]
Not really an issue. 
For a better performance, is there an API to save a training data as model and re-use it back? 

For instance,
```javascript
classifier.saveAsJson();

classifier.loadModel();
```

**Comment by andreekeberg** [comment]
Hi! There's no plan to add any method for directly saving the model to a file since I want to keep the API the same for both Node and the browser.

However, you can [serialize your model](https://github.com/andreekeberg/ml-classify-text-js#serializing-a-model), giving you a JSON object with all your training data, which can then easily be saved to a file using `JSON.stringify` and `fs.writeFile` in Node (or e.g posting the data to a backend from the browser/saving it to the browsers localStorage).

To load a saved model, you simply [pass a serialized model](https://github.com/andreekeberg/ml-classify-text-js/blob/master/docs/classifier.md#new-classifiermodel) either directly to the `Classifier` constructor, or a new `Model` instance and in turn pass that instance to your `Classifier` constructor.

Hope this helps, and be sure to let me know if you have any more questions!
